/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cd_zeng_base_jni_HelloWorld */

#ifndef _Included_cd_zeng_base_jni_HelloWorld
#define _Included_cd_zeng_base_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cd_zeng_base_jni_HelloWorld
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cd_zeng_base_jni_HelloWorld_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
